# GoReleaser configuration for Agent Deck
# Run: goreleaser release --clean
# Test: goreleaser release --snapshot --clean

version: 2

project_name: agent-deck

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: agent-deck
    main: ./cmd/agent-deck
    binary: agent-deck
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
    # Skip Windows - tmux not available
    ignore:
      - goos: windows

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: weykon
    name: agent-deck
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## Agent Deck v{{.Version}}

    Terminal session manager for AI coding agents.

    ### Installation

    **Homebrew (recommended):**
    ```bash
    brew install weykon/tap/agent-deck
    ```

    **Quick Install:**
    ```bash
    curl -fsSL https://raw.githubusercontent.com/weykon/agent-deck/main/install.sh | bash
    ```

    **Go Install:**
    ```bash
    go install github.com/weykon/agent-deck/cmd/agent-deck@v{{.Version}}
    ```

brews:
  - name: agent-deck
    repository:
      owner: weykon
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/weykon/agent-deck"
    description: "Terminal session manager for AI coding agents"
    license: "MIT"
    dependencies:
      - name: tmux
    test: |
      system "#{bin}/agent-deck", "version"
